name: Deploy Sphinx Docs

# Trigger the workflow on push to the main branch or on tag creation
on:
  push:
    tags:
      - "*"  # Trigger on any tag
  workflow_dispatch:  # Allow manual trigger

env:
  project_name: semantiva # Define a global variable for the project name
  python_version: '3.10.12'

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}

      - name: Install dependencies from pyproject.toml
        run: |
          pip install .
          pip install -e '.[dev]'  # Install dev dependencies if needed

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-autodoc-typehints sphinx-rtd-theme  # Add your Sphinx theme or plugins here

      - name: Create missing directories
        run: |
          mkdir -p docs/_static
          mkdir -p docs/_templates

      - name: Generate API Documentation
        run: |
          sphinx-apidoc -o docs/source/ -f semantiva/

      - name: Build Sphinx Documentation
        run: |
          sphinx-build -b html docs/source docs/build

      - name: Verify build directory
        run: ls -l docs/build || echo "Build directory not found!"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
